# Generated by Django 3.1.7 on 2021-04-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_auto_20210316_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
